Adding Power support(ppc64le) with continuous integration/testing to the project for architecture independent
latchset/kdcproxy pull request #55
Opened 2020-11-23 14:09 UTC by asellappen

I am part of IBM team and working on porting power arch to packages as continuous integration & testing.
This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing,We typically build applications for customers and ISVs, and while we don't use this package directly,
we do count on all of the packages in debian/ubuntu to build other packages. So we more likely have this as a second or third level dependency and couldn't tell you explicitly which features we use or our usage model,For more info tag @gerrith3.

Pls verify and merge

2020-11-24 19:23 UTC, frozencemetery commented
I will probably take this PR, but please understand that kdcproxy is a python package.  As such, architecture testing isn't a priority.  Eventually we are likely to move off Travis, and at the moment it looks like we will migrate to Github Actions, which as far as I can tell doesn't have "interesting" architecture support.

2020-11-24 20:34 UTC, frozencemetery requested changes
Your commit has:

    Author: Ubuntu <asellappen@yahoo.com>

Presumably this is not what you want.  Please fix to use your preferred name.

While you're doing that, please also clean up your commit message.  I suggest reading https://chris.beams.io/posts/git-commit/ and previous commit messages in the project to see what I'm looking for.

2020-11-25 17:50 UTC, frozencemetery requested changes
I really don't know what you expect here.

Instead of making either of the small changes requested (one of which is probably legally necessary), you changed the entire approach without comment and are now requesting review again.

I don't understand what response you expect here.

2020-11-25 17:50 UTC, closed without merging

2020-11-26 06:29 UTC, asellappen commented
It was not covered all python and tox envirmonet test earlier ,so i have modified the travis build to cover all the build as like amd64.

Please review kindly and provide feedback thanks